import { AIMode } from "../db";

/** Simulated assistant used when no provider key is configured. Mode-aware and multilingual-ish. */
export function demoResponse(mode: AIMode, messages: { role: string; content: string }[], lang: "en" | "es" | "fr"): string {
  const last = messages[messages.length - 1]?.content || "";
  const excerpt = last.length > 140 ? last.slice(0, 140).trim() + "…" : last;
  const L = lang;
  const note = L === "es" ? "\n\n_(Modo demo: conecta tu cuenta de Claude, GPT o Gemini en Conexiones de IA o configura una clave del servidor para respuestas reales.)_" : L === "fr" ? "\n\n_(Mode démo : connectez votre compte Claude, GPT ou Gemini dans Connexions IA ou configurez une clé serveur pour des réponses réelles.)_" : "\n\n_(Demo mode: connect your Claude, GPT or Gemini account in AI Connections, or set a server key, for live answers.)_";

  const byMode: Record<AIMode, Record<"en" | "es" | "fr", string>> = {
    chat: {
      en: `Good question. Let's pin down what you actually need to establish here.\n\n1. **Claim** — what is the specific statement this part of your thesis defends?\n2. **Evidence** — which data, sources or results support it, and which cut against it?\n3. **So what** — how does it move your overall argument forward?\n\nTell me which of the three feels weakest and we'll work on that first.`,
      es: `Buena pregunta. Concretemos qué necesitas establecer aquí.\n\n1. **Afirmación** — ¿qué enunciado concreto defiende esta parte de tu tesis?\n2. **Evidencia** — ¿qué datos, fuentes o resultados la apoyan, y cuáles la contradicen?\n3. **Relevancia** — ¿cómo hace avanzar tu argumento general?\n\nDime cuál de los tres te parece más débil y empezamos por ahí.`,
      fr: `Bonne question. Précisons ce que vous devez établir ici.\n\n1. **Affirmation** — quel énoncé précis cette partie défend-elle ?\n2. **Preuves** — quelles données ou sources l'appuient, lesquelles la contredisent ?\n3. **Portée** — en quoi fait-elle avancer votre argument général ?\n\nDites-moi lequel des trois vous semble le plus fragile.`,
    },
    brainstorm: {
      en: `Here are angles worth testing against your research question:\n\n- **Contrast case**: where does the phenomenon *not* happen, and why?\n- **Scale**: does the effect hold at individual, institutional and system level?\n- **Mechanism vs correlation**: what would distinguish the two in your data?\n- **Counter-argument**: the strongest objection a skeptical reviewer would raise\n- **Boundary conditions**: under which assumptions does your claim break?\n- **Practical stake**: who would change a decision if you are right?\n\nPick two and tell me why; I'll help you sharpen them into questions.`,
      es: `Ángulos que merece la pena contrastar con tu pregunta de investigación:\n\n- **Caso contrario**: ¿dónde *no* ocurre el fenómeno y por qué?\n- **Escala**: ¿se mantiene el efecto a nivel individual, institucional y de sistema?\n- **Mecanismo vs correlación**: ¿qué los distinguiría en tus datos?\n- **Contraargumento**: la objeción más fuerte de un revisor escéptico\n- **Condiciones límite**: ¿bajo qué supuestos falla tu afirmación?\n- **Implicación práctica**: ¿quién cambiaría una decisión si tienes razón?\n\nElige dos y dime por qué; te ayudo a convertirlos en preguntas.`,
      fr: `Pistes à confronter à votre question de recherche :\n\n- **Cas contraire** : où le phénomène *n'apparaît-il pas*, et pourquoi ?\n- **Échelle** : l'effet tient-il aux niveaux individuel, institutionnel, systémique ?\n- **Mécanisme vs corrélation** : qu'est-ce qui les distinguerait dans vos données ?\n- **Contre-argument** : l'objection la plus forte d'un relecteur sceptique\n- **Conditions limites** : sous quelles hypothèses votre affirmation échoue-t-elle ?\n- **Enjeu pratique** : qui changerait une décision si vous avez raison ?\n\nChoisissez-en deux ; je vous aide à les transformer en questions.`,
    },
    outline: {
      en: `Suggested structure for this section (fill each bullet with your own analysis):\n\n## 1. Framing\n- The specific problem this section addresses and why it matters here\n## 2. Prior work\n- 2-3 positions in the literature and where they disagree\n## 3. Your contribution\n- The claim, the method, the data\n## 4. Evidence\n- Key result(s), with a figure or table reference each\n## 5. Limitations & transition\n- What this section cannot show; what the next one takes up\n\nWant me to go one level deeper on any heading?`,
      es: `Estructura sugerida para esta sección (rellena cada punto con tu propio análisis):\n\n## 1. Planteamiento\n- El problema concreto que aborda esta sección y por qué importa aquí\n## 2. Trabajos previos\n- 2-3 posturas de la literatura y en qué discrepan\n## 3. Tu aportación\n- La afirmación, el método, los datos\n## 4. Evidencia\n- Resultado(s) clave, cada uno con referencia a figura o tabla\n## 5. Limitaciones y transición\n- Lo que esta sección no puede demostrar; lo que retoma la siguiente\n\n¿Quieres que profundice en algún apartado?`,
      fr: `Structure suggérée pour cette section (à remplir avec votre propre analyse) :\n\n## 1. Cadrage\n- Le problème précis traité et pourquoi il compte ici\n## 2. Travaux antérieurs\n- 2-3 positions de la littérature et leurs désaccords\n## 3. Votre contribution\n- L'affirmation, la méthode, les données\n## 4. Preuves\n- Résultat(s) clé(s), avec renvoi à une figure ou un tableau\n## 5. Limites et transition\n- Ce que la section ne montre pas ; ce que la suivante reprend\n\nSouhaitez-vous que je détaille un titre ?`,
    },
    critique: {
      en: `Reviewer notes on the passage (${excerpt ? `"${excerpt}"` : "no text provided"}):\n\n- **Argument**: the central claim is stated, but the causal link is asserted rather than shown. Which result supports it?\n- **Evidence**: one source carries most of the weight; add a second, ideally with a contrasting method.\n- **Structure**: the paragraph opens with background and reaches its point in the last sentence. Try leading with the point.\n- **Clarity**: two sentences exceed 40 words; split them.\n\nRevise and send it back; I'll check the new version.`,
      es: `Notas de revisión sobre el pasaje (${excerpt ? `"${excerpt}"` : "sin texto"}):\n\n- **Argumento**: la afirmación central se enuncia, pero el vínculo causal se afirma sin demostrarse. ¿Qué resultado la sostiene?\n- **Evidencia**: una sola fuente soporta casi todo el peso; añade una segunda, idealmente con otro método.\n- **Estructura**: el párrafo abre con contexto y llega a su punto en la última frase. Prueba a empezar por el punto.\n- **Claridad**: dos frases superan las 40 palabras; divídelas.\n\nRevísalo y envíamelo; comprobaré la nueva versión.`,
      fr: `Remarques de relecture sur le passage (${excerpt ? `« ${excerpt} »` : "aucun texte"}) :\n\n- **Argument** : l'affirmation centrale est posée, mais le lien causal est affirmé, non démontré. Quel résultat l'appuie ?\n- **Preuves** : une seule source porte l'essentiel ; ajoutez-en une seconde, idéalement avec une autre méthode.\n- **Structure** : le paragraphe commence par le contexte et n'atteint son point qu'à la dernière phrase. Commencez par le point.\n- **Clarté** : deux phrases dépassent 40 mots ; scindez-les.\n\nRévisez et renvoyez-moi la nouvelle version.`,
    },
    grammar: {
      en: `**Corrected passage** (your wording, minimal edits):\n\n> ${excerpt || "(paste the passage you wrote)"}\n\n**Changes**\n- Subject–verb agreement fixed in the second clause\n- Replaced an informal connector ("so") with "therefore"\n- Comma added after the introductory phrase\n- Kept your terminology and sentence order\n\nInsert only if these edits reflect what you meant.`,
      es: `**Pasaje corregido** (tu redacción, cambios mínimos):\n\n> ${excerpt || "(pega el pasaje que escribiste)"}\n\n**Cambios**\n- Concordancia sujeto-verbo corregida en la segunda oración\n- Conector informal sustituido por "por lo tanto"\n- Coma añadida tras la frase introductoria\n- Se mantienen tu terminología y el orden de las frases\n\nInsértalo solo si estos cambios reflejan lo que querías decir.`,
      fr: `**Passage corrigé** (votre formulation, modifications minimales) :\n\n> ${excerpt || "(collez le passage que vous avez écrit)"}\n\n**Modifications**\n- Accord sujet-verbe corrigé dans la deuxième proposition\n- Connecteur familier remplacé par « par conséquent »\n- Virgule ajoutée après la phrase introductive\n- Terminologie et ordre des phrases conservés\n\nInsérez uniquement si ces corrections reflètent votre intention.`,
    },
    summarize: {
      en: `Summary of the provided text:\n\n- Main claim: ${excerpt || "(no text provided)"}\n- Method/approach: stated briefly, evidence base not fully specified\n- Key finding: one central result, with limits noted\n- Relevance to your thesis: supports your framing; note the difference in scope\n\nIf this is your own draft rather than a source, use **Critique** instead.`,
      es: `Resumen del texto proporcionado:\n\n- Afirmación principal: ${excerpt || "(sin texto)"}\n- Método/enfoque: descrito brevemente, base de evidencia no del todo especificada\n- Hallazgo clave: un resultado central, con límites señalados\n- Relevancia para tu tesis: apoya tu planteamiento; anota la diferencia de alcance\n\nSi es tu propio borrador y no una fuente, usa **Revisión** en su lugar.`,
      fr: `Résumé du texte fourni :\n\n- Affirmation principale : ${excerpt || "(aucun texte)"}\n- Méthode : décrite brièvement, base de preuves incomplète\n- Résultat clé : un résultat central, avec ses limites\n- Pertinence pour votre mémoire : soutient votre cadrage ; notez la différence de portée\n\nSi c'est votre brouillon et non une source, utilisez plutôt **Critique**.`,
    },
    explain: {
      en: `**In one sentence**: the concept describes how a system's behaviour emerges from interactions that no single component controls.\n\n**Intuition**: think of traffic flow: no driver plans the jam, yet the jam is predictable from density and reaction times.\n\n**In your field**: it shows up when aggregate patterns cannot be reduced to individual choices; that is usually the point where a mixed-methods design earns its keep.\n\n**Keywords**: emergence, mechanism-based explanation, multilevel analysis.`,
      es: `**En una frase**: el concepto describe cómo el comportamiento de un sistema emerge de interacciones que ningún componente controla por sí solo.\n\n**Intuición**: piensa en el tráfico: ningún conductor planea el atasco, pero el atasco es predecible a partir de la densidad y los tiempos de reacción.\n\n**En tu campo**: aparece cuando los patrones agregados no se reducen a decisiones individuales; ahí suele justificarse un diseño mixto.\n\n**Palabras clave**: emergencia, explicación por mecanismos, análisis multinivel.`,
      fr: `**En une phrase** : le concept décrit comment le comportement d'un système émerge d'interactions qu'aucun composant ne contrôle seul.\n\n**Intuition** : le trafic routier : aucun conducteur ne planifie l'embouteillage, pourtant il est prévisible à partir de la densité et des temps de réaction.\n\n**Dans votre domaine** : il apparaît quand les motifs agrégés ne se réduisent pas aux choix individuels ; c'est là qu'une méthode mixte se justifie.\n\n**Mots-clés** : émergence, explication par mécanismes, analyse multiniveau.`,
    },
    citations: {
      en: `**APA 7**\n- In-text: (Reichstein et al., 2019)\n- Reference: Reichstein, M., Camps-Valls, G., Stevens, B., Jung, M., Denzler, J., Carvalhais, N., & Prabhat. (2019). Deep learning and process understanding for data-driven Earth system science. *Nature, 566*(7743), 195–204. https://doi.org/10.1038/s41586-019-0912-1\n\n**MLA 9**\n- Reichstein, Markus, et al. "Deep Learning and Process Understanding for Data-Driven Earth System Science." *Nature*, vol. 566, no. 7743, 2019, pp. 195–204.\n\nPaste the raw details of your reference (authors, year, title, venue) and I'll format it in your thesis style.`,
      es: `**APA 7**\n- En el texto: (Reichstein et al., 2019)\n- Referencia: Reichstein, M., Camps-Valls, G., Stevens, B., Jung, M., Denzler, J., Carvalhais, N., & Prabhat. (2019). Deep learning and process understanding for data-driven Earth system science. *Nature, 566*(7743), 195–204. https://doi.org/10.1038/s41586-019-0912-1\n\nPega los datos de tu referencia (autores, año, título, publicación) y la formateo en el estilo de tu tesis.`,
      fr: `**APA 7**\n- Dans le texte : (Reichstein et al., 2019)\n- Référence : Reichstein, M., Camps-Valls, G., Stevens, B., Jung, M., Denzler, J., Carvalhais, N., & Prabhat. (2019). Deep learning and process understanding for data-driven Earth system science. *Nature, 566*(7743), 195–204. https://doi.org/10.1038/s41586-019-0912-1\n\nCollez les détails de votre référence et je la mets en forme dans le style de votre mémoire.`,
    },
    gaps: {
      en: `Prioritized gaps:\n\n1. **Unsupported claim** — the improvement is stated as general but shown for one region. *Next step*: add a second region or narrow the claim.\n2. **Missing counter-argument** — physics-based models' interpretability advantage is not addressed. *Next step*: one paragraph on the trade-off.\n3. **Method detail** — how were hyper-parameters chosen? *Next step*: a short protocol in the methods appendix.\n4. **Terminology** — "accuracy" is used for both RMSE and classification. *Next step*: define once, use consistently.`,
      es: `Lagunas priorizadas:\n\n1. **Afirmación sin respaldo** — la mejora se presenta como general pero se muestra para una región. *Siguiente paso*: añadir una segunda región o acotar la afirmación.\n2. **Contraargumento ausente** — no se aborda la ventaja de interpretabilidad de los modelos físicos. *Siguiente paso*: un párrafo sobre esa compensación.\n3. **Detalle metodológico** — ¿cómo se eligieron los hiperparámetros? *Siguiente paso*: un protocolo breve en el anexo.\n4. **Terminología** — "precisión" se usa para RMSE y para clasificación. *Siguiente paso*: definirla una vez y usarla de forma coherente.`,
      fr: `Lacunes par priorité :\n\n1. **Affirmation non étayée** — l'amélioration est présentée comme générale mais montrée pour une seule région. *Étape suivante* : ajouter une région ou restreindre l'affirmation.\n2. **Contre-argument manquant** — l'avantage d'interprétabilité des modèles physiques n'est pas traité. *Étape suivante* : un paragraphe sur ce compromis.\n3. **Détail de méthode** — comment les hyperparamètres ont-ils été choisis ? *Étape suivante* : un protocole court en annexe.\n4. **Terminologie** — « précision » désigne à la fois RMSE et classification. *Étape suivante* : définir une fois, utiliser de façon cohérente.`,
    },
    copilot: {
      en: `Research copilot here. On "${excerpt || "your question"}": let's work it properly.\n\n**What I'd check first**\n- The design: what is the unit of analysis, and what varies between the groups or conditions you compare?\n- The assumption your method rests on (independence, normality, stationarity, saturation…) and how you will show it holds.\n- One paper that did something close: search for it with 2-3 of your key terms plus "methodology" and read its limitations section first.\n\n**Then**\n1. Sketch the analysis plan in five lines before touching data.\n2. Decide now what result would make you change your interpretation.\n3. Bring me the plan and I'll stress-test it.\n\nThe writing stays yours: I'll give you questions, structure and feedback, never paragraphs for the thesis.`,
      es: `Copiloto de investigación. Sobre "${excerpt || "tu pregunta"}": trabajémoslo bien.\n\n**Qué revisaría primero**\n- El diseño: cuál es la unidad de análisis y qué varía entre los grupos o condiciones que comparas.\n- El supuesto en que se apoya tu método (independencia, normalidad, estacionariedad, saturación…) y cómo vas a mostrar que se cumple.\n- Un artículo que hizo algo parecido: búscalo con 2-3 de tus términos clave más "methodology" y lee primero su sección de limitaciones.\n\n**Después**\n1. Esboza el plan de análisis en cinco líneas antes de tocar los datos.\n2. Decide ahora qué resultado te haría cambiar la interpretación.\n3. Tráeme el plan y lo pongo a prueba.\n\nLa redacción es tuya: te doy preguntas, estructura y crítica, nunca párrafos para la tesis.`,
      fr: `Copilote de recherche. Sur « ${excerpt || "votre question"} » : travaillons-le sérieusement.\n\n**Ce que je vérifierais d'abord**\n- Le plan : quelle est l'unité d'analyse et qu'est-ce qui varie entre les groupes ou conditions comparés ?\n- L'hypothèse sur laquelle repose votre méthode (indépendance, normalité, stationnarité, saturation…) et comment vous montrerez qu'elle tient.\n- Un article proche : cherchez-le avec 2-3 de vos mots-clés plus « methodology » et lisez d'abord sa section limites.\n\n**Ensuite**\n1. Esquissez le plan d'analyse en cinq lignes avant de toucher aux données.\n2. Décidez maintenant quel résultat vous ferait changer d'interprétation.\n3. Apportez-moi le plan, je le mettrai à l'épreuve.\n\nLa rédaction reste la vôtre : questions, structure et critique, jamais de paragraphes pour le mémoire.`,
    },
    paraphrase_check: {
      en: `**Verdict: too close to the source.** Your passage keeps the source's sentence order and ~60% of its wording; a citation alone does not make that acceptable.\n\nHow to fix it (without me writing it):\n- Close the source; write the idea from memory in two sentences\n- Change the *structure*: lead with the consequence, then the cause\n- Keep only technical terms verbatim, and cite\n\nSend the rewrite and I'll compare again.`,
      es: `**Veredicto: demasiado cerca de la fuente.** Tu pasaje conserva el orden de frases y ~60% de las palabras del original; citar no basta para que sea aceptable.\n\nCómo arreglarlo (sin que yo lo escriba):\n- Cierra la fuente; escribe la idea de memoria en dos frases\n- Cambia la *estructura*: empieza por la consecuencia, luego la causa\n- Conserva solo los términos técnicos literales, y cita\n\nEnvíame la nueva versión y vuelvo a comparar.`,
      fr: `**Verdict : trop proche de la source.** Votre passage garde l'ordre des phrases et ~60 % des mots ; la citation seule ne suffit pas.\n\nComment corriger (sans que je l'écrive) :\n- Fermez la source ; écrivez l'idée de mémoire en deux phrases\n- Changez la *structure* : la conséquence d'abord, puis la cause\n- Ne gardez que les termes techniques, et citez\n\nEnvoyez la réécriture et je compare à nouveau.`,
    },
  };

  const greeting = /^(hi|hello|hey|hola|bonjour|salut)\b/i.test(last.trim());
  if (greeting && mode === "chat") {
    return (L === "es" ? "¡Hola! Soy Thesisfic AI. Puedo ayudarte a hacer lluvia de ideas, estructurar capítulos, revisar borradores, corregir gramática y formatear citas, siempre sin escribir tu tesis por ti. ¿En qué trabajamos hoy?" : L === "fr" ? "Bonjour ! Je suis Thesisfic AI. Je peux vous aider à réfléchir, structurer vos chapitres, relire vos brouillons, corriger la grammaire et mettre en forme vos citations, sans jamais écrire votre mémoire à votre place. Sur quoi travaillons-nous ?" : "Hello! I'm Thesisfic AI. I can help you brainstorm, structure chapters, review drafts, fix grammar and format citations, always without writing your thesis for you. What are we working on today?") + note;
  }
  return byMode[mode][L] + note;
}
